fix NoSuchMethodError
E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No direct method <init>(IIJJIILjava/lang/String;)V in class Landroid/app/AppOpsManager$OpEntry; or its super classes (declaration of 'android.app.AppOpsManager$OpEntry' appears in /system/framework/framework.jar:classes2.dex)